Repository entando/entando-plugin-jpredis, pull requests merged in 2021-07, with the labels that each got.

#7 ENG-2178: Fix Caches definitions
  pom.xml
  src/main/resources/spring/plugins/jpredis/aps/baseManagersConfig.xml
Labels: approved, size/M

#8 ENG-2471 NewGen workflow v1.0.1
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
Labels: prepared, size/L

#11 ENG-2554: Added Notify Manager for redis
  pom.xml
  src/main/java/org/entando/entando/plugins/jpredis/aps/system/notify/RedisNotifyManager.java
  src/main/java/org/entando/entando/plugins/jpredis/aps/system/redis/CacheConfig.java
  src/main/resources/spring/plugins/jpredis/aps/baseManagersConfig.xml
  src/test/java/org/entando/entando/plugins/jpredis/aps/system/notify/DefaultRedisPubSubListener.java
  src/test/java/org/entando/entando/plugins/jpredis/aps/system/notify/RedisNotifyManagerIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpredis/aps/system/notify/RedisNotifyManagerTest.java
  src/test/java/org/entando/entando/plugins/jpredis/aps/system/notify/TestEvent.java
  src/test/java/org/entando/entando/plugins/jpredis/aps/system/services/CacheInfoManagerIntegrationTest.java
Labels: prepared, size/XL
